using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class text_4_1 : MonoBehaviour
{
    public static int num = 0;
    public static GameObject button_;
    public static int cnt = 0; //st atic ë³€ìˆ˜ë¡œ ìˆ˜ì • 
    public static Text typingText; 
    public static GameObject fadeout;
    public int i;

    

//     //string -> narration
    private static string text_1="ì‘ì—…ì‹¤ ë¬¸ì´ ì—´ë¦¬ìë§ˆì ë¹ ë¥¸ ì†ë„ë¡œ 1ì¸µìœ¼ë¡œ ê°€ëŠ” ê³„ë‹¨ì„ ë‚´ë ¤ê°”ë‹¤.";
    private static string text_2="ìƒëª…ì„ ì±…ì„ì§„ë‹¤ëŠ” ìƒê° í•˜ë‚˜ë§Œìœ¼ë¡œ ë²„í…¨ì™”ëŠ”ë°â€¦â€¦. \nì‹œë£¨ì—ê²Œ ë¬´ìŠ¨ ì¼ì´ ìƒê¸´ë‹¤ë©´ ì •ë§ ë¬´ë„ˆì§ˆì§€ë„ ëª°ë¼.";
    private static string text_3="[ ì§€ê¸ˆ ì²­ì£¼ë¡œ ì™€ ì¤„ ìˆ˜ ìˆì–´? ê¸‰í•´ğŸ¥º ]";
    private static string text_4="ë¬´ìŠ¨ ì¼ì¸ë°?";
    private static string text_5="ì•„ë¹ ê°€ ì°¨ê³  ë’¤ì— ìˆ¨ì–´ìˆëŠ” ìƒˆë¼ê³ ì–‘ì´ë¥¼ ë°œê²¬í–ˆëŠ”ë° \nì—„ë§ˆ ì•„ë“¤ë†ˆì´ ì•Œë ˆë¥´ê¸°ê°€ ìˆì–´ì„œ ìš°ë¦¬ ì§‘ì—ì„  ëª» í‚¤ìš°ê±°ë“  \ní˜¹ì‹œ í‚¤ìš¸ ìƒê° ìˆë‚˜ í•˜ê³ ã… ã… ";
    private static string text_6="ì‹¤ìˆ˜ë¡œ ë©”ì‹œì§€ ì°½ì„ ëˆ„ë¥´ëŠ” \në°”ëŒì— ì½ìŒ í‘œì‹œê°€ ì—†ì–´ì¡Œë‹¤.";
    private static string text_7="ì•„, ì–´ë–¡í•˜ì§€. \në‚˜ ê³ ì–‘ì´ í•œ ë²ˆë„ í‚¤ì›Œë³¸ ì  ì—†ëŠ”ë°.";
    private static string text_8="ë‚´ê°€ ë©”ì‹œì§€ë¥¼ ì½ì€ ê±¸ í™•ì¸í–ˆëŠ”ì§€ \nì§™ì€ ê°ˆìƒ‰ í„¸ì— ì†œë°©ë§ì´ë§Œ \ní•˜ì–€ ì–‘ë§ì„ ì‹ ì€ ìƒˆë¼ ê³ ì–‘ì´ \nì˜ìƒì´ ë‚ ë¼ ì™”ë‹¤.";
    private static string text_9="[ ì•„ë¹ ê°€ ì ‘ì¢…ì€ ë‹¤ ë§ì¶°ì„œ ë³´ë‚´ì¤€ëŒ€. ì‘? ]";
    private static string text_10="ì…ì–‘ ê³µê³ ëŠ” ì˜¬ë ¸ì–´?";
    private static string text_11="ì›¬ë§Œí•˜ë©´ ë¯¿ì„ ìˆ˜ ìˆëŠ” ì‚¬ëŒí•œí…Œ \në§¡ê¸°ê³  ì‹¶ë‹¨ ë§ì´ì•¼. \nì´ìƒí•œ ì‚¬ëŒí•œí…Œ ë³´ëƒˆë‹¤ê°€ í•™ëŒ€ë¼ë„ \në‹¹í•˜ë©´ ì–´ë–¡í•´? \ní‰ìƒ ì£„ì±…ê°ì— ì‹œë‹¬ë¦´ ê±°ì•¼.";
    private static string text_12="í˜¼ì ì‚¬ëŠ” ëŒ€í•™ìƒì¹˜ê³  ì§‘ì´ ì¢ì§€ëŠ” ì•Šì§€ë§Œ, \nê·¸ë˜ë„ ê³ ì–‘ì´ë¥¼ í‚¤ìš°ê¸°ì— \nì í•©í•œ í™˜ê²½ì¸ì§€ëŠ” í™•ì‹ ì´ ë“¤ì§€ ì•Šì•˜ë‹¤.";
    private static string text_13="ê²Œë‹¤ê°€ ë‚˜ëŠ” ì•„ì§ ìƒë‹´ ì¹˜ë£Œë„ ë°›ê³  ìˆê³ â€¦. \në‚˜ ê°™ì€ ì‚¬ëŒì´ ë™ë¬¼ì„ í‚¤ì›Œë„ ë˜ëŠ” ê±¸ê¹Œ?";
    private static string text_14="í•˜ì§€ë§Œ ê±±ì •ìœ¼ë¡œ ê°€ë“í•œ ë¨¸ë¦¬ì™€ëŠ” ë°˜ëŒ€ë¡œ \nì´ë¯¸ ë‚´ ì†ì€ ì²­ì£¼ë¡œ ê°€ëŠ” ê¸°ì°¨í‘œë¥¼ ì˜ˆë§¤í•˜ê³  ìˆì—ˆë‹¤.";
    private static string text_15="ì•Œì•˜ì–´, ë‚´ë ¤ê°ˆê²Œ.\n\n[ ì§„ì§œì§€? ì˜ í‚¤ì›Œì£¼ê¸°ë¡œ ì•½ì†í•œ ê±°ë‹¤? ]\n\nê·¸ë ‡ë‹¤ë‹ˆê¹\n\n[ ê·¸ëŸ¼ ì´ë¦„ì€ ë­˜ë¡œ í• ë˜? ]\n\nì´ë¦„?";
    private static string text_16="í—ˆí”¼ìŠ¤ ë•Œë¬¸ì— ëˆˆê³±ì´ ì”ëœ© ê»´ì„œ \nëˆˆë„ ì œëŒ€ë¡œ ëª» ëœ¨ë©´ì„œë„ \nì•…ì°©ê°™ì´ ìš°ìœ ë¥¼ \në°›ì•„ë¨¹ëŠ” ëª¨ìŠµì´ ê¼­â€¦â€¦.";
    private static string text_17="ì‹œë£¨. ì‹œë£¨ë¡œ í• ë˜.";
    private static string text_18="[ ì‹œë£¨?? ê·¸ê²Œ ë­ì•¼;\nì›ë˜ ê°•ì•„ì§€ ê³ ì–‘ì´ ì´ë¦„ì€ ë¨¹ëŠ” ê±°ë¡œ í•˜ëŠ” ê±° ì•„ë‹ˆë¬ì–´ ]";
    private static string text_19="ë‚˜ ê¸°ì°¨í‘œ ì·¨ì†Œí•œë‹¤?";
    private static string text_20="ë‹µì´ ì—†ì–´ì„œ ë‹¤ë¥¸ ì…ì–‘ì²˜ë¥¼ \nì°¾ì•˜ë‚˜ í–ˆë”ë‹ˆ ì–¼ë§ˆ ì§€ë‚˜ì§€ ì•Šì•„ \nì‹œë£¨ë¼ê³  ì íŒ \nì´ë¦„í‘œë¥¼ ë‹¨ ì‚¼ìƒ‰ ê³ ì–‘ì´, \nê·¸ëŸ¬ë‹ˆê¹Œ ì‹œë£¨ì˜ ì‚¬ì§„ì„ ë°›ì•˜ë‹¤.";
    private static string text_21="ë°‘ì—ëŠ” ë³´ë¼ìƒ‰ ë„¤ì˜¨ì‚¬ì¸ìœ¼ë¡œ \nâ€˜ì§‘ì‚¬ ë„ˆë¥¼ ì„ íƒí–ˆë‹¤! ë‚˜ë¥¼ ì˜ í‚¤ì›Œë¼ëƒ¥! \nê·¸ë ‡ì§€ ì•Šìœ¼ë©´ ê³ ì–‘ì´ì˜ ì €ì£¼ë¥¼ ë‚´ë¦¬ê² ë‹¤ëƒ¥!â€™\nì´ë¼ê³  ì í˜€ ìˆì—ˆë‹¤.";
    private static string text_22="\"í•˜ì—¬íŠ¼, ëª» ë§ë¦°ë‹¤ë‹ˆê¹Œ.\"\n[ ê·¸ë˜ ì•½ì†í• ê²Œ ]";
    
    static IEnumerator coroutine =  Typing(text_1);
    static IEnumerator coroutine1 = Typing(text_2);
    static IEnumerator coroutine2 = Typing(text_3);       
    static IEnumerator coroutine3 = Typing(text_4);
    static IEnumerator coroutine4 = Typing(text_5);
    static IEnumerator coroutine5 = Typing(text_6);
    static IEnumerator coroutine6 = Typing(text_7);
    static IEnumerator coroutine7 = Typing(text_8);
    static IEnumerator coroutine8=  Typing(text_9);
    static IEnumerator coroutine9 = Typing(text_10);
    static IEnumerator coroutine10 = Typing(text_11);       
    static IEnumerator coroutine11 = Typing(text_12);
    static IEnumerator coroutine12 = Typing(text_13);
    static IEnumerator coroutine13 = Typing(text_14);
    static IEnumerator coroutine14 = Typing(text_15);
    static IEnumerator coroutine15 = Typing(text_16);
    static IEnumerator coroutine16 = Typing(text_17);
    static IEnumerator coroutine17 = Typing(text_18);       
    static IEnumerator coroutine18 = Typing(text_19);
    static IEnumerator coroutine19 = Typing(text_20);
    static IEnumerator coroutine20 = Typing(text_21);
    static IEnumerator coroutine21 = Typing(text_22);
   


    public static void ìŠ¤í‚µë²„íŠ¼í´ë¦­(){
        Debug.Log("skipbutton is clicked! num="+num);
        num+=1;
    }

    static IEnumerator Typing(string message)
    { 
        Text typingText = GameObject.Find("general text").GetComponent<Text>();
        Debug.Log(typingText);
        Debug.Log(message);
        
        //message=text_1;
        for (int i = 0; i < message.Length; i++) 
        { 
            typingText.text = message.Substring(0, i + 1); 
            yield return new WaitForSeconds(0.05f);

            if(num%3==1){
                num++;
                Debug.Log("coroutine is stopped+num"+num);
                yield break; //ì½”ë£¨í‹´ì¢…ë£Œ
                //ì—¬ê¸°ì„œ ê·¸ëƒ¥ ëŠê³ , updateì—ì„œ ë‹¤ìŒ ì‹œë‚˜ë¦¬ì˜¤ ì¶œë ¥í•´ì£¼ê¸°
            }//ì½”ë£¨í‹´ì´ ì¤‘ê°„ì— ëë‚˜ëŠ” ê²ƒì´ ì•„ë‹ˆë¼ ê·¸ëƒ¥ ë‚˜ê°€ë©´? ã…‡ã…‹ã…‡ã…‹
           
            }
            num++;
            Debug.Log("user didn't skip the text+num"+num);
        
    
    }

    

    // Start is called before the first frame update
   void Start()
    {
       Button ìŠ¤í‚µ = GameObject.Find("skipButton").GetComponent<Button>();
       ìŠ¤í‚µ.onClick.AddListener(text_4_1.ìŠ¤í‚µë²„íŠ¼í´ë¦­);//adlistnerë¡œ ë¶ˆëŸ¬ì˜¤ë ¤ë©´ static voidì—¬ì•¼ í•œë‹¤.



        Debug.Log("coroutin is started! #3-1 num"+num);
        StartCoroutine(coroutine);
        
    }

//     // Update is called once per frame
    void Update(){
        //Debug.Log(num);
        if(num==2){
            Debug.Log("coroutine is started!  num"+num);
            StartCoroutine(coroutine1); 
            num++;
            //StartCoroutine(coroutine1);
        }
        if(num==5){
            Debug.Log("coroutine is started!  num"+num);
            StartCoroutine(coroutine2);
            num++;
        }
        if(num==8){
            Debug.Log("coroutine is started!  num"+num);
            StartCoroutine(coroutine3);
            num++;
        }
        if(num==11){
            StartCoroutine(coroutine4);
            Debug.Log("coroutine is started!  num"+num);
            num++;
        }
        if(num==14){
            StartCoroutine(coroutine5);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button
        }
        
        if(num==17){
            StartCoroutine(coroutine6);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==20){
            StartCoroutine(coroutine7);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==23){
            StartCoroutine(coroutine8);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==26){
            StartCoroutine(coroutine9);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==29){
            StartCoroutine(coroutine10);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==32){
            StartCoroutine(coroutine11);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==35){
            StartCoroutine(coroutine12);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==38){
            StartCoroutine(coroutine13);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==41){
            StartCoroutine(coroutine14);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==44){
            StartCoroutine(coroutine15);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==47){
            StartCoroutine(coroutine16);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==50){
            StartCoroutine(coroutine17);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==53){
            StartCoroutine(coroutine18);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==56){
            StartCoroutine(coroutine19);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==59){
            StartCoroutine(coroutine20);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
        if(num==62){
            StartCoroutine(coroutine21);
            Debug.Log("coroutine is started!  num"+num);
            num++;//activate button    
        }
    }
}